### ISSUE TITLE
Weird button layout

### ISSUE THREAD

**Issue by Kuuuube** [themoeway/yomitan-wiki#32]
![image](https://github.com/user-attachments/assets/a103c30e-8f42-40f8-85eb-5fdb699fc914)

1 2 3
4

This is not an issue with wrapping, it will also never expand to show all 4 in the same line no matter how big the window is.

**Comment by jamesmaa** [comment]
I wasn't sure how to fix this. Was thinking about centering `Get Started` but idk how 😭

**Comment by Kuuuube** [comment]
I would probably take the Get Started button out of the grid entirely and just have it stretch to the full width. Theres also now the issue of the grid looking weird when it goes to a 2x2 so maybe we should also not let that happen and make it only 3x1 or 1x3.
