### ISSUE TITLE
Add big extension download buttons

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/yomitan-wiki#6]
<img width="616" alt="image" src="https://github.com/user-attachments/assets/d05203d9-8b90-498e-9d3d-ae2c2e97d696">

These are pretty small

**Comment by cashewnuttynuts** [comment]
Those are not meant to be download buttons, theyre just decorative badges
Buttons are here:
![image](https://github.com/user-attachments/assets/3653599c-bcc9-4776-a7fc-57700ffa696a)

**Comment by cashewnuttynuts** [comment]
I'll remove the badges and replace them with download buttons
